name: Test site

on:
  push:

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install PHP dependencies
        uses: php-actions/composer@v6
        with:
          dev: yes
          args: --ignore-platform-reqs

      - name: Bring site up
        run: ./vendor/bin/sail up -d

      - name: Run php cs fixer
        run: ./vendor/bin/php-cs-fixer fix

      - name: Apply php-cs-fixer changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply php-cs-fixer changes

      - name: Run phpstan
        run: ./vendor/bin/phpstan analyze app
        continue-on-error: true

      - name: Run tests
        run: ./artisan test

      - name: Run phpinsights
        run: php artisan insights --no-interaction --min-quality=65 --min-complexity=80 --min-architecture=75 --min-style=65
