name: Run CI Checks 🔎

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install PHP dependencies
        uses: php-actions/composer@v6
        with:
          dev: yes
          args: --ignore-platform-reqs

      - name: Install js dependencies
        run: npm install

      - name: Copy .env file
        run: cp .env.ci .env

      # Pull the latest image to build, and avoid caching pull-only images.
      # (docker pull is faster than caching in most cases.)
      - run: docker-compose pull --ignore-pull-failures
        continue-on-error: true

      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Bring site up
        run: ./vendor/bin/sail up -d

      - name: Run php cs fixer
        run: ./vendor/bin/php-cs-fixer fix

      - name: Apply php-cs-fixer changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply php-cs-fixer changes
          file_pattern: app tests database config routes

      - name: Run phpstan
        run: ./vendor/bin/phpstan analyze app
        continue-on-error: true

      - name: Run tests
        run: ./vendor/bin/sail artisan test --parallel

      - name: Run phpinsights
        run: ./vendor/bin/sail artisan insights --no-interaction --min-quality=65 --min-complexity=80 --min-architecture=75 --min-style=65
